const express = require("express")
const router = express.Router()
const {signUp, logIn, dashboard, postSignUp, postLogIn, fetchData, fetch, auth, fetchUserData} = require("../controllers/server")

router.get('/',signUp)
router.get('/signup',signUp)
router.get('/login',logIn)
router.get('/dashboard',dashboard)
router.post('/signup',postSignUp)
router.post('/login',postLogIn)
router.post('/dashboard/google',fetch)
router.get('/users/:email',fetchData)
router.get('/users/fetch/:email',fetchUserData)
router.patch('/users/:email',auth)
module.exports = router